// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Mismo orden de precedencia que Next.js: `.env.local` —que es donde escribe
// `vercel env pull`— gana sobre `.env`. dotenv nunca pisa una variable ya
// definida, así que en el build de Vercel, donde vienen del entorno, no hace
// nada.
loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Las migraciones toman un advisory lock de Postgres, y ese lock no
    // sobrevive a un pooler en modo transacción: contra la URL pooled,
    // `migrate deploy` falla de manera intermitente. Neon publica la conexión
    // directa en DATABASE_URL_UNPOOLED, que es la que corresponde acá; en local
    // esa variable no existe y cae en DATABASE_URL.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
