// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "./prisma/load-env";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Las migraciones toman un advisory lock de Postgres, y ese lock no
    // sobrevive a un pooler en modo transacción: contra la URL pooled,
    // `migrate deploy` falla de manera intermitente. Neon publica la conexión
    // directa en DATABASE_URL_UNPOOLED, que es la que corresponde acá; en local
    // esa variable no existe y cae en DATABASE_URL.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
